[client]
showSidebarNavigation = false
toolbarMode = "minimal"

[theme]
base="dark"
primaryColor="#FF4B4B"
backgroundColor="#1E1E1E"
secondaryBackgroundColor="#262626"
textColor="#FFFFFF"


[server]
enableXsrfProtection = false
headless = true


[global]
disableWidgetStateDuplicationWarning = false

[browser]
gatherUsageStats = false

